const keyMirror = require('src/utils/keyMirror');

const Names = keyMirror({
  Fighter: true,
  Gladiator: true,
  Monk: true,
  Hunter: true,
  Assassin: true,
  Berserker: true,
  'Abyssal Knight': true,
  'Chaos Knight': true,
  Skald: true,
  Enchanter: true,
  Transmuter: true,
  'Arcane Marksman': true,
  Warper: true,
  Wizard: true,
  Conjurer: true,
  Summoner: true,
  Necromancer: true,
  'Fire Elementalist': true,
  'Ice Elementalist': true,
  'Air Elementalist': true,
  'Earth Elementalist': true,
  'Venom Mage': true,
  Artificer: true,
  Wanderer: true,
});

const Abbreviations = {
  Fighter: 'Fi',
  Gladiator: 'Gl',
  Monk: 'Mo',
  Hunter: 'Hu',
  Assassin: 'As',
  Berserker: 'Be',
  'Abyssal Knight': 'AK',
  'Chaos Knight': 'CK',
  Skald: 'Sk',
  Enchanter: 'En',
  Transmuter: 'Tm',
  'Arcane Marksman': 'AM',
  Warper: 'Wr',
  Wizard: 'Wz',
  Conjurer: 'Cj',
  Summoner: 'Su',
  Necromancer: 'Ne',
  'Fire Elementalist': 'FE',
  'Ice Elementalist': 'IE',
  'Air Elementalist': 'AE',
  'Earth Elementalist': 'EE',
  'Venom Mage': 'VM',
  Artificer: 'Ar',
  Wanderer: 'Wn',
};

module.exports = {
  Names,
  Abbreviations,
  Regex: new RegExp(`(${Object.keys(Names).join('|')})`),
};
