const keyMirror = require('src/utils/keyMirror');

const Backgrounds = keyMirror({
  AE: true,
  AK: true,
  AM: true,
  Ar: true,
  As: true,
  Be: true,
  Cj: true,
  CK: true,
  De: true,
  EE: true,
  En: true,
  FE: true,
  Gl: true,
  Hu: true,
  IE: true,
  Mo: true,
  Ne: true,
  Sk: true,
  Su: true,
  Tm: true,
  VM: true,
  Wn: true,
  Wr: true,
  Wz: true,
  Fi: true,
});

const Names = {
  [Backgrounds.AE]: 'Air Elementalist',
  [Backgrounds.AK]: 'Abyssal Knight',
  [Backgrounds.AM]: 'Arcane Marksman',
  [Backgrounds.Ar]: 'Artificer',
  [Backgrounds.As]: 'Assassin',
  [Backgrounds.Be]: 'Berserker',
  [Backgrounds.Cj]: 'Conjurer',
  [Backgrounds.CK]: 'Chaos Knight',
  [Backgrounds.De]: 'Delver',
  [Backgrounds.EE]: 'Earth Elementalist',
  [Backgrounds.En]: 'Enchanter',
  [Backgrounds.FE]: 'Fire Elementalist',
  [Backgrounds.Fi]: 'Fighter',
  [Backgrounds.Gl]: 'Gladiator',
  [Backgrounds.Hu]: 'Hunter',
  [Backgrounds.IE]: 'Ice Elementalist',
  [Backgrounds.Mo]: 'Monk',
  [Backgrounds.Ne]: 'Necromancer',
  [Backgrounds.Sk]: 'Skald',
  [Backgrounds.Su]: 'Summoner',
  [Backgrounds.Tm]: 'Transmuter',
  [Backgrounds.VM]: 'Venom Mage',
  [Backgrounds.Wn]: 'Wanderer',
  [Backgrounds.Wr]: 'Warper',
  [Backgrounds.Wz]: 'Wizard',
};

module.exports = {
  ...Backgrounds,
  Names,
  Regex: new RegExp(`(${Object.values(Names).join('|')})`),
};
