const keyMirror = require('src/utils/keyMirror');

const Gods = keyMirror({
  Ashenzari: true,
  Beogh: true,
  Cheibriados: true,
  Dithmenos: true,
  Elyvilon: true,
  Fedhas: true,
  Gozag: true,
  Hepliaklqana: true,
  Ignis: true,
  Jiyva: true,
  Kikubaaqudgha: true,
  Lugonu: true,
  Makhleb: true,
  Nemelex: true,
  Okawaru: true,
  Qazlal: true,
  Ru: true,
  SifMuna: true,
  Trog: true,
  Uskayaw: true,
  Vehumet: true,
  WuJian: true,
  Xom: true,
  Yredelemnul: true,
  Zin: true,
  ShiningOne: true,
});

const Names = {
  [Gods.Ashenzari]: 'Ashenzari',
  [Gods.Beogh]: 'Beogh',
  [Gods.Cheibriados]: 'Cheibriados',
  [Gods.Dithmenos]: 'Dithmenos',
  [Gods.Elyvilon]: 'Elyvilon',
  [Gods.Fedhas]: 'Fedhas',
  [Gods.Gozag]: 'Gozag',
  [Gods.Hepliaklqana]: 'Hepliaklqana',
  [Gods.Ignis]: 'Ignis',
  [Gods.Jiyva]: 'Jiyva',
  [Gods.Kikubaaqudgha]: 'Kikubaaqudgha',
  [Gods.Lugonu]: 'Lugonu',
  [Gods.Makhleb]: 'Makhleb',
  [Gods.Nemelex]: 'Nemelex',
  [Gods.Okawaru]: 'Okawaru',
  [Gods.Qazlal]: 'Qazlal',
  [Gods.Ru]: 'Ru',
  [Gods.SifMuna]: 'Sif Muna',
  [Gods.Trog]: 'Trog',
  [Gods.Uskayaw]: 'Uskayaw',
  [Gods.Vehumet]: 'Vehumet',
  [Gods.WuJian]: 'Wu Jian',
  [Gods.Xom]: 'Xom',
  [Gods.Yredelemnul]: 'Yredelemnul',
  [Gods.Zin]: 'Zin',
  [Gods.ShiningOne]: 'Shining One',
};

module.exports = {
  ...Gods,
  Keys: Gods,
  Names,
  Regex: new RegExp(`(${Object.values(Names).join('|')})`),
};
