const keyMirror = require('src/utils/keyMirror');

const Species = keyMirror({
  Barachi: true,
  Centaur: true,
  'Deep Dwarf': true,
  'Deep Elf': true,
  Demigod: true,
  Demonspawn: true,
  Draconian: true,
  Felid: true,
  Formicid: true,
  Gargoyle: true,
  Ghoul: true,
  Gnoll: true,
  Halfling: true,
  'Hill Orc': true,
  Human: true,
  Kobold: true,
  Merfolk: true,
  Minotaur: true,
  Mummy: true,
  Naga: true,
  Octopode: true,
  Ogre: true,
  Spriggan: true,
  Tengu: true,
  Troll: true,
  Vampire: true,
  'Vine Stalker': true,
});

const Abbreviations = {
  Barachi: 'Ba',
  Centaur: 'Ce',
  'Deep Dwarf': 'DD',
  'Deep Elf': 'DE',
  Demigod: 'Dg',
  Demonspawn: 'Ds',
  Draconian: 'Dr',
  Felid: 'Fe',
  Formicid: 'Fo',
  Gargoyle: 'Gr',
  Ghoul: 'Gh',
  Gnoll: 'Gn',
  Halfling: 'Ha',
  'Hill Orc': 'HO',
  Human: 'Hu',
  Kobold: 'Ko',
  Merfolk: 'Mf',
  Minotaur: 'Mi',
  Mummy: 'Mu',
  Naga: 'Na',
  Octopode: 'Op',
  Ogre: 'Og',
  Spriggan: 'Sp',
  Tengu: 'Te',
  Troll: 'Tr',
  Vampire: 'Vp',
  'Vine Stalker': 'VS',
};

module.exports = {
  ...Species,
  Abbreviations,
  Regex: new RegExp(`(${Object.keys(Species).join('|')})`),
};
