// Generated from `scripts/build_spell_list 0.27 0.28 0.29 0.30 0.31 0.32`

export const List = [
  'Agony',
  'Airstrike',
  "Alistair's Intoxication",
  'Anguish',
  'Animate Armour',
  'Animate Dead',
  'Animate Skeleton',
  'Apportation',
  'Arcjolt',
  'Beastly Appendage',
  'Blade Hands',
  'Blink',
  'Bolt of Magma',
  'Bombard',
  "Borgnjor's Revivification",
  "Borgnjor's Vile Clutch",
  "Brom's Barrelling Boulder",
  'Call Canine Familiar',
  'Call Imp',
  'Cause Fear',
  'Chain Lightning',
  "Cigotuvi's Dreadful Rot",
  "Cigotuvi's Putrefaction",
  'Confusing Touch',
  'Conjure Ball Lightning',
  'Conjure Flame',
  'Corona',
  'Corpse Rot',
  'Curse of Agony',
  'Dazzling Flash',
  'Death Channel',
  "Death's Door",
  'Dimensional Bullseye',
  'Discord',
  'Disjunction',
  'Dispel Undead',
  'Dispersal',
  'Dragon Form',
  "Dragon's Call",
  'Enfeeble',
  'Ensorcelled Hibernation',
  "Eringya's Noxious Bog",
  'Excruciating Wounds',
  'Fire Storm',
  'Fireball',
  'Flame Wave',
  'Foxfire',
  'Freeze',
  'Freezing Cloud',
  'Frozen Ramparts',
  'Fugue of the Fallen',
  'Fulminant Prism',
  'Fulsome Fusillade',
  "Gell's Gavotte",
  "Gell's Gravitas",
  'Grave Claw',
  'Hailstorm',
  'Haunt',
  'Hellfire Mortar',
  'Hoarfrost Cannonade',
  'Ice Form',
  'Ignite Poison',
  'Ignition',
  'Infestation',
  'Inner Flame',
  'Invisibility',
  'Iron Shot',
  'Irradiate',
  "Iskenderun's Battlesphere",
  "Iskenderun's Mystic Blast",
  'Jinxbite',
  'Kiss of Death',
  "Leda's Liquefaction",
  "Lee's Rapid Deconstruction",
  "Lehudib's Crystal Spear",
  'Lesser Beckoning',
  'Lightning Bolt',
  'Magic Dart',
  'Magnavolt',
  'Malign Gateway',
  'Manifold Assault',
  "Martyr's Knell",
  "Maxwell's Capacitive Coupling",
  "Maxwell's Portable Piledriver",
  'Mephitic Cloud',
  'Mercury Vapours',
  'Metabolic Englaciation',
  'Momentum Strike',
  'Monstrous Menagerie',
  'Necromutation',
  'Necrotise',
  "Olgreb's Toxic Radiance",
  'Orb of Destruction',
  "Ozocubu's Armour",
  "Ozocubu's Refrigeration",
  'Pain',
  'Passage of Golubria',
  'Passwall',
  'Permafrost Eruption',
  'Petrify',
  'Plasma Beam',
  'Poisonous Vapours',
  'Polar Vortex',
  'Portal Projectile',
  'Rimeblight',
  'Sandblast',
  'Scorch',
  'Sculpt Simulacrum',
  'Searing Ray',
  'Shadow Creatures',
  'Shatter',
  'Shock',
  'Sigil of Binding',
  'Silence',
  'Simulacrum',
  'Slow',
  'Soul Splinter',
  'Spellforged Servitor',
  'Spider Form',
  'Starburst',
  'Static Discharge',
  'Statue Form',
  'Sticky Flame',
  'Sting',
  'Stone Arrow',
  'Storm Form',
  'Sublimation of Blood',
  'Summon Blazeheart Golem',
  'Summon Cactus Giant',
  'Summon Forest',
  'Summon Guardian Golem',
  'Summon Horrible Things',
  'Summon Hydra',
  'Summon Ice Beast',
  'Summon Lightning Spire',
  'Summon Mana Viper',
  'Summon Small Mammal',
  'Swiftness',
  'Teleport Other',
  "Tukima's Dance",
  'Vampiric Draining',
  "Vhi's Electric Charge",
  'Volatile Blastmotes',
  'Wereblood',
  "Yara's Violent Unravelling",
];
