// Generated from `scripts/build_unrand_list 0.27 0.28 0.29 0.30 0.31 0.32 0.33`

export const List = [
  'amulet of Elemental Vulnerability',
  'amulet of the Air',
  'amulet of the Four Winds',
  'amulet of Vitality',
  'arbalest "Damnation"',
  'arc blade',
  'autumn katana',
  "Black Knight's barding",
  'brooch of Shielding',
  "captain's cutlass",
  "Charlatan's Orb",
  "Cigotuvi's embrace",
  'cloak of Starlight',
  'cloak of the Thief',
  'consecrated labrys',
  'crown of Dyrovepreva',
  'crown of vainglory',
  'crystal ball of Wucad Mu',
  'dagger "Morg"',
  'dark maul',
  "Delatra's gloves",
  'demon blade "Leech"',
  'demon trident "Rift"',
  'demon whip "Spellbinder"',
  'dreamshard necklace',
  'Elemental Staff',
  'eveningstar "Brilliance"',
  "fencer's gloves",
  'Force Lance',
  'frozen axe "Frostbite"',
  'fungal fisticloak',
  'gauntlets of War',
  'giant club "Skullcrusher"',
  'glaive of Prune',
  'glaive of the Guard',
  'gloves of the gadgeteer',
  'great mace "Firestarter"',
  'great mace "Undeadhunter"',
  'greatsling "Punk"',
  'hand cannon "Mule"',
  'hat of Pondering',
  'hat of the Alchemist',
  'hat of the Bear Spirit',
  'heavy crossbow "Sniper"',
  "Hermit's Pendant",
  'hood of the Assassin',
  "justicar's regalia",
  "Kryia's mail coat",
  'lajatang of Order',
  'lance "Wyrmbane"',
  "Lear's hauberk",
  'lightning scales',
  'Lochaber axe',
  'longbow "Zephyr"',
  'macabre finger necklace',
  'mace of Variability',
  "Mad Mage's Maulers",
  'Majin-Bo',
  'mask of the Dragon',
  "Maxwell's patent armour",
  "Maxwell's thermic engine",
  'mithril axe "Arga"',
  'moon troll leather armour',
  'morningstar "Eos"',
  'mountain boots',
  'necklace of Bloodlust',
  'obsidian axe',
  'orange crystal plate armour',
  'pair of quick blades "Gyre" and "Gimble"',
  'plutonium sword',
  'ratskin cloak',
  'ring of Shadows',
  'ring of the Hare',
  'ring of the Mage',
  'ring of the Octopus King',
  'ring of the Tortoise',
  'robe of Augmentation',
  'robe of Clouds',
  'robe of Folly',
  'robe of Misfortune',
  'robe of Night',
  'robe of Vines',
  'salamander hide armour',
  'scales of the Dragon King',
  'sceptre of Torment',
  'scythe "Finisher"',
  'scythe of Curses',
  'seven-league boots',
  'shield of Resistance',
  'shield of the Gong',
  'shillelagh "Devastator"',
  'Singing Sword',
  'skin of Zhor',
  'skull of Zonguldrok',
  'slick slippers',
  'sling "Punk"',
  'sphere of Battle',
  "Spriggan's Knife",
  'staff of Battle',
  'staff of Olgreb',
  'staff of the Meek',
  'staff of Wucad Mu',
  'storm bow',
  "Storm Queen's Shield",
  'sword of Power',
  'sword of the Doom Knight',
  'sword of Zonguldrok',
  'Throatcutter',
  'toga "Victory"',
  'tower shield of Ignorance',
  'trident of the Octopus King',
  'trishula "Condemnation"',
  "Vampire's Tooth",
  "warlock's mirror",
  'whip "Snakebite"',
  "woodcutter's axe",
  'Wrath of Trog',
  "zealot's sword",
];

//prettier-ignore
export const Metadata = [
  {"image_url":"https://raw.githubusercontent.com/crawl/crawl/0.29.1/crawl-ref/source/rltiles/item/amulet/artefact/urand_elemental_vulnerability.png","name":"amulet of Elemental Vulnerability","id":"UNRAND_ELEMENTAL_VULNERABILITY","version":"0.29"},
  {"image_url":"https://raw.githubusercontent.com/crawl/crawl/0.27.1/crawl-ref/source/rltiles/item/amulet/artefact/urand_air.png","name":"amulet of the Air","id":"UNRAND_AIR","version":"0.27"},
  {"image_url":"https://raw.githubusercontent.com/crawl/crawl/0.27.1/crawl-ref/source/rltiles/item/amulet/artefact/urand_four_winds.png","name":"amulet of the Four Winds","id":"UNRAND_FOUR_WINDS","version":"0.27"},
  {"image_url":"https://raw.githubusercontent.com/crawl/crawl/0.27.1/crawl-ref/source/rltiles/item/amulet/artefact/urand_vitality.png","name":"amulet of Vitality","id":"UNRAND_VITALITY","version":"0.27"},
  {"image_url":"https://raw.githubusercontent.com/crawl/crawl/0.27.1/crawl-ref/source/rltiles/item/weapon/artefact/urand_damnation.png","name":"arbalest \"Damnation\"","id":"UNRAND_DAMNATION","version":"0.27"},
  {"image_url":"https://raw.githubusercontent.com/crawl/crawl/0.27.1/crawl-ref/source/rltiles/item/weapon/artefact/urand_arc_blade.png","name":"arc blade","id":"UNRAND_ARC_BLADE","version":"0.27"},
  {"image_url":"https://raw.githubusercontent.com/crawl/crawl/0.27.1/crawl-ref/source/rltiles/item/weapon/artefact/urand_katana.png","name":"autumn katana","id":"UNRAND_AUTUMN_KATANA","version":"0.27"},
  {"image_url":"https://raw.githubusercontent.com/crawl/crawl/0.27.1/crawl-ref/source/rltiles/item/armour/artefact/urand_bk_barding.png","name":"Black Knight's barding","id":"UNRAND_BLACK_KNIGHT_HORSE","version":"0.27"},
  {"image_url":"https://raw.githubusercontent.com/crawl/crawl/0.27.1/crawl-ref/source/rltiles/item/amulet/artefact/urand_brooch_of_shielding.png","name":"brooch of Shielding","id":"UNRAND_SHIELDING","version":"0.27"},
  {"image_url":"https://raw.githubusercontent.com/crawl/crawl/0.27.1/crawl-ref/source/rltiles/item/weapon/artefact/urand_cutlass.png","name":"captain's cutlass","id":"UNRAND_CAPTAIN","version":"0.27"},
  {"image_url":"https://raw.githubusercontent.com/crawl/crawl/0.32.1/crawl-ref/source/rltiles/item/armour/artefact/urand_charlatan.png","name":"Charlatan's Orb","id":"UNRAND_CHARLATANS_ORB","version":"0.32"},
  {"image_url":"https://raw.githubusercontent.com/crawl/crawl/0.27.1/crawl-ref/source/rltiles/item/armour/artefact/urand_cigotuvi.png","name":"Cigotuvi's embrace","id":"UNRAND_EMBRACE","version":"0.27"},
  {"image_url":"https://raw.githubusercontent.com/crawl/crawl/0.27.1/crawl-ref/source/rltiles/item/armour/artefact/urand_starlight.png","name":"cloak of Starlight","id":"UNRAND_STARLIGHT","version":"0.27"},
  {"image_url":"https://raw.githubusercontent.com/crawl/crawl/0.27.1/crawl-ref/source/rltiles/item/armour/artefact/urand_thief.png","name":"cloak of the Thief","id":"UNRAND_THIEF","version":"0.27"},
  {"image_url":"https://raw.githubusercontent.com/crawl/crawl/0.30.0/crawl-ref/source/rltiles/item/weapon/artefact/spwpn_holy_axe.png","name":"consecrated labrys","id":"UNRAND_HOLY_AXE","version":"0.30"},
  {"image_url":"https://raw.githubusercontent.com/crawl/crawl/0.27.1/crawl-ref/source/rltiles/item/armour/artefact/urand_dyrovepreva.png","name":"crown of Dyrovepreva","id":"UNRAND_DYROVEPREVA","version":"0.27"},
  {"image_url":"https://raw.githubusercontent.com/crawl/crawl/0.33.1/crawl-ref/source/rltiles/item/armour/artefact/urand_crown_of_vainglory.png","name":"crown of vainglory","id":"UNRAND_VAINGLORY","version":"0.33"},
  {"image_url":"https://raw.githubusercontent.com/crawl/crawl/0.30.0/crawl-ref/source/rltiles/item/armour/artefact/urand_wucad_mu.png","name":"crystal ball of Wucad Mu","id":"UNRAND_WUCAD_MU","version":"0.30"},
  {"image_url":"https://raw.githubusercontent.com/crawl/crawl/0.27.1/crawl-ref/source/rltiles/item/weapon/artefact/urand_morg.png","name":"dagger \"Morg\"","id":"UNRAND_MORG","version":"0.27"},
  {"image_url":"https://raw.githubusercontent.com/crawl/crawl/0.27.1/crawl-ref/source/rltiles/item/weapon/artefact/urand_dark_maul.png","name":"dark maul","id":"UNRAND_DARK_MAUL","version":"0.27"},
  {"image_url":"https://raw.githubusercontent.com/crawl/crawl/0.28.0/crawl-ref/source/rltiles/item/armour/artefact/urand_delatra.png","name":"Delatra's gloves","id":"UNRAND_DELATRAS_GLOVES","version":"0.28"},
  {"image_url":"https://raw.githubusercontent.com/crawl/crawl/0.27.1/crawl-ref/source/rltiles/item/weapon/artefact/urand_leech.png","name":"demon blade \"Leech\"","id":"UNRAND_LEECH","version":"0.27"},
  {"image_url":"https://raw.githubusercontent.com/crawl/crawl/0.27.1/crawl-ref/source/rltiles/item/weapon/artefact/urand_rift.png","name":"demon trident \"Rift\"","id":"UNRAND_RIFT","version":"0.27"},
  {"image_url":"https://raw.githubusercontent.com/crawl/crawl/0.27.1/crawl-ref/source/rltiles/item/weapon/artefact/urand_spellbinder.png","name":"demon whip \"Spellbinder\"","id":"UNRAND_SPELLBINDER","version":"0.27"},
  {"image_url":"https://raw.githubusercontent.com/crawl/crawl/0.28.0/crawl-ref/source/rltiles/item/amulet/artefact/urand_dreamshard.png","name":"dreamshard necklace","id":"UNRAND_DREAMSHARD_NECKLACE","version":"0.28"},
  {"image_url":"https://raw.githubusercontent.com/crawl/crawl/0.27.1/crawl-ref/source/rltiles/item/weapon/artefact/urand_elemental.png","name":"Elemental Staff","id":"UNRAND_ELEMENTAL_STAFF","version":"0.27"},
  {"image_url":"https://raw.githubusercontent.com/crawl/crawl/0.32.1/crawl-ref/source/rltiles/item/weapon/artefact/urand_brilliance.png","name":"eveningstar \"Brilliance\"","id":"UNRAND_BRILLIANCE","version":"0.32"},
  {"image_url":"https://raw.githubusercontent.com/crawl/crawl/0.27.1/crawl-ref/source/rltiles/item/armour/artefact/urand_fencer.png","name":"fencer's gloves","id":"UNRAND_FENCERS","version":"0.27"},
  {"image_url":"https://raw.githubusercontent.com/crawl/crawl/0.30.0/crawl-ref/source/rltiles/item/weapon/artefact/urand_force_lance.png","name":"Force Lance","id":"UNRAND_FORCE_LANCE","version":"0.30"},
  {"image_url":"https://raw.githubusercontent.com/crawl/crawl/0.27.1/crawl-ref/source/rltiles/item/weapon/artefact/urand_frostbite.png","name":"frozen axe \"Frostbite\"","id":"UNRAND_FROSTBITE","version":"0.27"},
  {"image_url":"https://raw.githubusercontent.com/crawl/crawl/0.33.1/crawl-ref/source/rltiles/item/armour/artefact/urand_fungal_fisticloak.png","name":"fungal fisticloak","id":"UNRAND_FISTICLOAK","version":"0.33"},
  {"image_url":"https://raw.githubusercontent.com/crawl/crawl/0.27.1/crawl-ref/source/rltiles/item/armour/artefact/urand_war.png","name":"gauntlets of War","id":"UNRAND_WAR","version":"0.27"},
  {"image_url":"https://raw.githubusercontent.com/crawl/crawl/0.27.1/crawl-ref/source/rltiles/item/weapon/artefact/urand_skullcrusher.png","name":"giant club \"Skullcrusher\"","id":"UNRAND_SKULLCRUSHER","version":"0.27"},
  {"image_url":"https://raw.githubusercontent.com/crawl/crawl/0.27.1/crawl-ref/source/rltiles/item/weapon/artefact/spwpn_glaive_of_prune.png","name":"glaive of Prune","id":"UNRAND_PRUNE","version":"0.27"},
  {"image_url":"https://raw.githubusercontent.com/crawl/crawl/0.27.1/crawl-ref/source/rltiles/item/weapon/artefact/urand_guard.png","name":"glaive of the Guard","id":"UNRAND_GUARD","version":"0.27"},
  {"image_url":"https://raw.githubusercontent.com/crawl/crawl/0.32.1/crawl-ref/source/rltiles/item/armour/artefact/urand_gadgeteer.png","name":"gloves of the gadgeteer","id":"UNRAND_GADGETEER","version":"0.32"},
  {"image_url":"https://raw.githubusercontent.com/crawl/crawl/0.27.1/crawl-ref/source/rltiles/item/weapon/artefact/urand_firestarter.png","name":"great mace \"Firestarter\"","id":"UNRAND_FIRESTARTER","version":"0.27"},
  {"image_url":"https://raw.githubusercontent.com/crawl/crawl/0.27.1/crawl-ref/source/rltiles/item/weapon/artefact/urand_undeadhunter.png","name":"great mace \"Undeadhunter\"","id":"UNRAND_UNDEADHUNTER","version":"0.27"},
  {"image_url":"https://raw.githubusercontent.com/crawl/crawl/0.29.1/crawl-ref/source/rltiles/item/weapon/artefact/urand_punk.png","name":"greatsling \"Punk\"","id":"UNRAND_PUNK","version":"0.29"},
  {"image_url":"https://raw.githubusercontent.com/crawl/crawl/0.31.0/crawl-ref/source/rltiles/item/weapon/artefact/spwpn_mule.png","name":"hand cannon \"Mule\"","id":"UNRAND_MULE","version":"0.31"},
  {"image_url":"https://raw.githubusercontent.com/crawl/crawl/0.27.1/crawl-ref/source/rltiles/item/armour/artefact/urand_pondering.png","name":"hat of Pondering","id":"UNRAND_PONDERING","version":"0.27"},
  {"image_url":"https://raw.githubusercontent.com/crawl/crawl/0.27.1/crawl-ref/source/rltiles/item/armour/artefact/urand_alchemist.png","name":"hat of the Alchemist","id":"UNRAND_ALCHEMIST","version":"0.27"},
  {"image_url":"https://raw.githubusercontent.com/crawl/crawl/0.27.1/crawl-ref/source/rltiles/item/armour/artefact/urand_bear.png","name":"hat of the Bear Spirit","id":"UNRAND_BEAR_SPIRIT","version":"0.27"},
  {"image_url":"https://raw.githubusercontent.com/crawl/crawl/0.27.1/crawl-ref/source/rltiles/item/weapon/artefact/urand_sniper.png","name":"heavy crossbow \"Sniper\"","id":"UNRAND_SNIPER","version":"0.27"},
  {"image_url":"https://raw.githubusercontent.com/crawl/crawl/0.30.0/crawl-ref/source/rltiles/item/amulet/artefact/urand_hermit_pendant.png","name":"Hermit's Pendant","id":"UNRAND_HERMITS_PENDANT","version":"0.30"},
  {"image_url":"https://raw.githubusercontent.com/crawl/crawl/0.27.1/crawl-ref/source/rltiles/item/armour/artefact/urand_hood_assassin.png","name":"hood of the Assassin","id":"UNRAND_HOOD_ASSASSIN","version":"0.27"},
  {"image_url":"https://raw.githubusercontent.com/crawl/crawl/0.33.1/crawl-ref/source/rltiles/item/armour/artefact/urand_justicars_regalia.png","name":"justicar's regalia","id":"UNRAND_JUSTICARS_REGALIA","version":"0.33"},
  {"image_url":"https://raw.githubusercontent.com/crawl/crawl/0.27.1/crawl-ref/source/rltiles/item/armour/artefact/urand_kryias.png","name":"Kryia's mail coat","id":"UNRAND_KRYIAS","version":"0.27"},
  {"image_url":"https://raw.githubusercontent.com/crawl/crawl/0.27.1/crawl-ref/source/rltiles/item/weapon/artefact/urand_order.png","name":"lajatang of Order","id":"UNRAND_ORDER","version":"0.27"},
  {"image_url":"https://raw.githubusercontent.com/crawl/crawl/0.27.1/crawl-ref/source/rltiles/item/weapon/artefact/urand_wyrmbane.png","name":"lance \"Wyrmbane\"","id":"UNRAND_WYRMBANE","version":"0.27"},
  {"image_url":"https://raw.githubusercontent.com/crawl/crawl/0.27.1/crawl-ref/source/rltiles/item/armour/artefact/urand_lear.png","name":"Lear's hauberk","id":"UNRAND_LEAR","version":"0.27"},
  {"image_url":"https://raw.githubusercontent.com/crawl/crawl/0.27.1/crawl-ref/source/rltiles/item/armour/artefact/urand_lightning_scales.png","name":"lightning scales","id":"UNRAND_LIGHTNING_SCALES","version":"0.27"},
  {"image_url":"https://raw.githubusercontent.com/crawl/crawl/0.29.1/crawl-ref/source/rltiles/item/weapon/artefact/urand_lochaber_axe.png","name":"Lochaber axe","id":"UNRAND_LOCHABER_AXE","version":"0.29"},
  {"image_url":"https://raw.githubusercontent.com/crawl/crawl/0.27.1/crawl-ref/source/rltiles/item/weapon/artefact/urand_zephyr.png","name":"longbow \"Zephyr\"","id":"UNRAND_ZEPHYR","version":"0.27"},
  {"image_url":"https://raw.githubusercontent.com/crawl/crawl/0.27.1/crawl-ref/source/rltiles/item/amulet/artefact/urand_finger.png","name":"macabre finger necklace","id":"UNRAND_FINGER_AMULET","version":"0.27"},
  {"image_url":"https://raw.githubusercontent.com/crawl/crawl/0.27.1/crawl-ref/source/rltiles/item/weapon/artefact/spwpn_mace_of_variability.png","name":"mace of Variability","id":"UNRAND_VARIABILITY","version":"0.27"},
  {"image_url":"https://raw.githubusercontent.com/crawl/crawl/0.28.0/crawl-ref/source/rltiles/item/armour/artefact/urand_power_gloves.png","name":"Mad Mage's Maulers","id":"UNRAND_POWER_GLOVES","version":"0.28"},
  {"image_url":"https://raw.githubusercontent.com/crawl/crawl/0.27.1/crawl-ref/source/rltiles/item/weapon/artefact/spwpn_majin.png","name":"Majin-Bo","id":"UNRAND_MAJIN","version":"0.27"},
  {"image_url":"https://raw.githubusercontent.com/crawl/crawl/0.27.1/crawl-ref/source/rltiles/item/armour/artefact/urand_dragonmask.png","name":"mask of the Dragon","id":"UNRAND_DRAGONMASK","version":"0.27"},
  {"image_url":"https://raw.githubusercontent.com/crawl/crawl/0.27.1/crawl-ref/source/rltiles/item/armour/artefact/urand_maxwell.png","name":"Maxwell's patent armour","id":"UNRAND_MAXWELL","version":"0.27"},
  {"image_url":"https://raw.githubusercontent.com/crawl/crawl/0.27.1/crawl-ref/source/rltiles/item/weapon/artefact/urand_thermic_engine.png","name":"Maxwell's thermic engine","id":"UNRAND_THERMIC_ENGINE","version":"0.27"},
  {"image_url":"https://raw.githubusercontent.com/crawl/crawl/0.27.1/crawl-ref/source/rltiles/item/weapon/artefact/urand_arga.png","name":"mithril axe \"Arga\"","id":"UNRAND_ARGA","version":"0.27"},
  {"image_url":"https://raw.githubusercontent.com/crawl/crawl/0.27.1/crawl-ref/source/rltiles/item/armour/artefact/urand_moon_troll_leather_armour.png","name":"moon troll leather armour","id":"UNRAND_MOON_TROLL_LEATHER_ARMOUR","version":"0.27"},
  {"image_url":"https://raw.githubusercontent.com/crawl/crawl/0.27.1/crawl-ref/source/rltiles/item/weapon/artefact/urand_eos.png","name":"morningstar \"Eos\"","id":"UNRAND_EOS","version":"0.27"},
  {"image_url":"https://raw.githubusercontent.com/crawl/crawl/0.29.1/crawl-ref/source/rltiles/item/armour/artefact/urand_mountain.png","name":"mountain boots","id":"UNRAND_MOUNTAIN_BOOTS","version":"0.29"},
  {"image_url":"https://raw.githubusercontent.com/crawl/crawl/0.27.1/crawl-ref/source/rltiles/item/amulet/artefact/urand_bloodlust.png","name":"necklace of Bloodlust","id":"UNRAND_BLOODLUST","version":"0.27"},
  {"image_url":"https://raw.githubusercontent.com/crawl/crawl/0.27.1/crawl-ref/source/rltiles/item/weapon/artefact/spwpn_demon_axe.png","name":"obsidian axe","id":"UNRAND_DEMON_AXE","version":"0.27"},
  {"image_url":"https://raw.githubusercontent.com/crawl/crawl/0.27.1/crawl-ref/source/rltiles/item/armour/artefact/urand_orange_crystal.png","name":"orange crystal plate armour","id":"UNRAND_ORANGE_CRYSTAL_PLATE_ARMOUR","version":"0.27"},
  {"image_url":"https://raw.githubusercontent.com/crawl/crawl/0.27.1/crawl-ref/source/rltiles/item/weapon/artefact/urand_gyre.png","name":"pair of quick blades \"Gyre\" and \"Gimble\"","id":"UNRAND_GYRE","version":"0.27"},
  {"image_url":"https://raw.githubusercontent.com/crawl/crawl/0.27.1/crawl-ref/source/rltiles/item/weapon/artefact/urand_plutonium.png","name":"plutonium sword","id":"UNRAND_PLUTONIUM_SWORD","version":"0.27"},
  {"image_url":"https://raw.githubusercontent.com/crawl/crawl/0.27.1/crawl-ref/source/rltiles/item/armour/artefact/urand_ratskin_cloak.png","name":"ratskin cloak","id":"UNRAND_RATSKIN_CLOAK","version":"0.27"},
  {"image_url":"https://raw.githubusercontent.com/crawl/crawl/0.27.1/crawl-ref/source/rltiles/item/ring/artefact/urand_shadows.png","name":"ring of Shadows","id":"UNRAND_SHADOWS","version":"0.27"},
  {"image_url":"https://raw.githubusercontent.com/crawl/crawl/0.27.1/crawl-ref/source/rltiles/item/ring/artefact/urand_hare.png","name":"ring of the Hare","id":"UNRAND_HARE","version":"0.27"},
  {"image_url":"https://raw.githubusercontent.com/crawl/crawl/0.27.1/crawl-ref/source/rltiles/item/ring/artefact/urand_mage.png","name":"ring of the Mage","id":"UNRAND_MAGE","version":"0.27"},
  {"image_url":"https://raw.githubusercontent.com/crawl/crawl/0.27.1/crawl-ref/source/rltiles/item/ring/artefact/urand_octoring.png","name":"ring of the Octopus King","id":"UNRAND_OCTOPUS_KING_RING","version":"0.27"},
  {"image_url":"https://raw.githubusercontent.com/crawl/crawl/0.27.1/crawl-ref/source/rltiles/item/ring/artefact/urand_tortoise.png","name":"ring of the Tortoise","id":"UNRAND_TORTOISE","version":"0.27"},
  {"image_url":"https://raw.githubusercontent.com/crawl/crawl/0.27.1/crawl-ref/source/rltiles/item/armour/artefact/urand_augmentation.png","name":"robe of Augmentation","id":"UNRAND_AUGMENTATION","version":"0.27"},
  {"image_url":"https://raw.githubusercontent.com/crawl/crawl/0.27.1/crawl-ref/source/rltiles/item/armour/artefact/urand_clouds.png","name":"robe of Clouds","id":"UNRAND_RCLOUDS","version":"0.27"},
  {"image_url":"https://raw.githubusercontent.com/crawl/crawl/0.27.1/crawl-ref/source/rltiles/item/armour/artefact/urand_folly.png","name":"robe of Folly","id":"UNRAND_FOLLY","version":"0.27"},
  {"image_url":"https://raw.githubusercontent.com/crawl/crawl/0.27.1/crawl-ref/source/rltiles/item/armour/artefact/urand_misfortune.png","name":"robe of Misfortune","id":"UNRAND_MISFORTUNE","version":"0.27"},
  {"image_url":"https://raw.githubusercontent.com/crawl/crawl/0.27.1/crawl-ref/source/rltiles/item/armour/artefact/urand_night.png","name":"robe of Night","id":"UNRAND_NIGHT","version":"0.27"},
  {"image_url":"https://raw.githubusercontent.com/crawl/crawl/0.27.1/crawl-ref/source/rltiles/item/armour/artefact/urand_vines.png","name":"robe of Vines","id":"UNRAND_VINES","version":"0.27"},
  {"image_url":"https://raw.githubusercontent.com/crawl/crawl/0.27.1/crawl-ref/source/rltiles/item/armour/artefact/urand_salamander.png","name":"salamander hide armour","id":"UNRAND_SALAMANDER","version":"0.27"},
  {"image_url":"https://raw.githubusercontent.com/crawl/crawl/0.27.1/crawl-ref/source/rltiles/item/armour/artefact/urand_dragon_king.png","name":"scales of the Dragon King","id":"UNRAND_DRAGON_KING","version":"0.27"},
  {"image_url":"https://raw.githubusercontent.com/crawl/crawl/0.27.1/crawl-ref/source/rltiles/item/weapon/artefact/spwpn_sceptre_of_torment.png","name":"sceptre of Torment","id":"UNRAND_TORMENT","version":"0.27"},
  {"image_url":"https://raw.githubusercontent.com/crawl/crawl/0.27.1/crawl-ref/source/rltiles/item/weapon/artefact/urand_finisher.png","name":"scythe \"Finisher\"","id":"UNRAND_FINISHER","version":"0.27"},
  {"image_url":"https://raw.githubusercontent.com/crawl/crawl/0.27.1/crawl-ref/source/rltiles/item/weapon/artefact/spwpn_scythe_of_curses.png","name":"scythe of Curses","id":"UNRAND_CURSES","version":"0.27"},
  {"image_url":"https://raw.githubusercontent.com/crawl/crawl/0.27.1/crawl-ref/source/rltiles/item/armour/artefact/urand_seven_league_boots.png","name":"seven-league boots","id":"UNRAND_SEVEN_LEAGUE_BOOTS","version":"0.27"},
  {"image_url":"https://raw.githubusercontent.com/crawl/crawl/0.27.1/crawl-ref/source/rltiles/item/armour/artefact/urand_resistance.png","name":"shield of Resistance","id":"UNRAND_RESISTANCE","version":"0.27"},
  {"image_url":"https://raw.githubusercontent.com/crawl/crawl/0.27.1/crawl-ref/source/rltiles/item/armour/artefact/urand_gong.png","name":"shield of the Gong","id":"UNRAND_GONG","version":"0.27"},
  {"image_url":"https://raw.githubusercontent.com/crawl/crawl/0.27.1/crawl-ref/source/rltiles/item/weapon/artefact/urand_shillelagh.png","name":"shillelagh \"Devastator\"","id":"UNRAND_DEVASTATOR","version":"0.27"},
  {"image_url":"https://raw.githubusercontent.com/crawl/crawl/0.27.1/crawl-ref/source/rltiles/item/weapon/artefact/spwpn_singing_sword.png","name":"Singing Sword","id":"UNRAND_SINGING_SWORD","version":"0.27"},
  {"image_url":"https://raw.githubusercontent.com/crawl/crawl/0.27.1/crawl-ref/source/rltiles/item/armour/artefact/urand_zhor.png","name":"skin of Zhor","id":"UNRAND_ZHOR","version":"0.27"},
  {"image_url":"https://raw.githubusercontent.com/crawl/crawl/0.33.1/crawl-ref/source/rltiles/item/armour/artefact/urand_skull_of_zonguldrok.png","name":"skull of Zonguldrok","id":"UNRAND_SKULL_OF_ZONGULDROK","version":"0.33"},
  {"image_url":"https://raw.githubusercontent.com/crawl/crawl/0.30.0/crawl-ref/source/rltiles/item/armour/artefact/urand_slippers.png","name":"slick slippers","id":"UNRAND_SLICK_SLIPPERS","version":"0.30"},
  {"image_url":"https://raw.githubusercontent.com/crawl/crawl/0.27.1/crawl-ref/source/rltiles/item/weapon/artefact/urand_punk.png","name":"sling \"Punk\"","id":"UNRAND_PUNK_v27","version":"0.27"},
  {"image_url":"https://raw.githubusercontent.com/crawl/crawl/0.30.0/crawl-ref/source/rltiles/item/armour/artefact/urand_battle.png","name":"sphere of Battle","id":"UNRAND_BATTLE","version":"0.30"},
  {"image_url":"https://raw.githubusercontent.com/crawl/crawl/0.27.1/crawl-ref/source/rltiles/item/weapon/artefact/urand_spriggans_knife.png","name":"Spriggan's Knife","id":"UNRAND_SPRIGGANS_KNIFE","version":"0.27"},
  {"image_url":"https://raw.githubusercontent.com/crawl/crawl/0.27.1/crawl-ref/source/rltiles/item/weapon/artefact/urand_staff_of_battle.png","name":"staff of Battle","id":"UNRAND_BATTLE_v27","version":"0.27"},
  {"image_url":"https://raw.githubusercontent.com/crawl/crawl/0.27.1/crawl-ref/source/rltiles/item/weapon/artefact/spwpn_staff_of_olgreb.png","name":"staff of Olgreb","id":"UNRAND_OLGREB","version":"0.27"},
  {"image_url":"https://raw.githubusercontent.com/crawl/crawl/0.28.0/crawl-ref/source/rltiles/item/weapon/artefact/urand_meek.png","name":"staff of the Meek","id":"UNRAND_MEEK","version":"0.28"},
  {"image_url":"https://raw.githubusercontent.com/crawl/crawl/0.27.1/crawl-ref/source/rltiles/item/weapon/artefact/spwpn_wucad_mu.png","name":"staff of Wucad Mu","id":"UNRAND_WUCAD_MU_v27","version":"0.27"},
  {"image_url":"https://raw.githubusercontent.com/crawl/crawl/0.27.1/crawl-ref/source/rltiles/item/weapon/artefact/urand_storm_bow.png","name":"storm bow","id":"UNRAND_STORM_BOW","version":"0.27"},
  {"image_url":"https://raw.githubusercontent.com/crawl/crawl/0.30.0/crawl-ref/source/rltiles/item/armour/artefact/urand_storm_queen.png","name":"Storm Queen's Shield","id":"UNRAND_STORM_QUEEN","version":"0.30"},
  {"image_url":"https://raw.githubusercontent.com/crawl/crawl/0.27.1/crawl-ref/source/rltiles/item/weapon/artefact/spwpn_sword_of_power.png","name":"sword of Power","id":"UNRAND_POWER","version":"0.27"},
  {"image_url":"https://raw.githubusercontent.com/crawl/crawl/0.32.1/crawl-ref/source/rltiles/item/weapon/artefact/urand_doom_knight.png","name":"sword of the Doom Knight","id":"UNRAND_DOOM_KNIGHT","version":"0.32"},
  {"image_url":"https://raw.githubusercontent.com/crawl/crawl/0.27.1/crawl-ref/source/rltiles/item/weapon/artefact/spwpn_sword_of_zonguldrok.png","name":"sword of Zonguldrok","id":"UNRAND_ZONGULDROK","version":"0.27"},
  {"image_url":"https://raw.githubusercontent.com/crawl/crawl/0.28.0/crawl-ref/source/rltiles/item/weapon/artefact/urand_throatcutter.png","name":"Throatcutter","id":"UNRAND_THROATCUTTER","version":"0.28"},
  {"image_url":"https://raw.githubusercontent.com/crawl/crawl/0.30.0/crawl-ref/source/rltiles/item/armour/artefact/urand_victor.png","name":"toga \"Victory\"","id":"UNRAND_VICTORY","version":"0.30"},
  {"image_url":"https://raw.githubusercontent.com/crawl/crawl/0.27.1/crawl-ref/source/rltiles/item/armour/artefact/urand_ignorance.png","name":"tower shield of Ignorance","id":"UNRAND_IGNORANCE","version":"0.27"},
  {"image_url":"https://raw.githubusercontent.com/crawl/crawl/0.27.1/crawl-ref/source/rltiles/item/weapon/artefact/urand_octopus_king.png","name":"trident of the Octopus King","id":"UNRAND_OCTOPUS_KING","version":"0.27"},
  {"image_url":"https://raw.githubusercontent.com/crawl/crawl/0.29.1/crawl-ref/source/rltiles/item/weapon/artefact/urand_condemnation.png","name":"trishula \"Condemnation\"","id":"UNRAND_CONDEMNATION","version":"0.29"},
  {"image_url":"https://raw.githubusercontent.com/crawl/crawl/0.27.1/crawl-ref/source/rltiles/item/weapon/artefact/spwpn_vampires_tooth.png","name":"Vampire's Tooth","id":"UNRAND_VAMPIRES_TOOTH","version":"0.27"},
  {"image_url":"https://raw.githubusercontent.com/crawl/crawl/0.27.1/crawl-ref/source/rltiles/item/armour/artefact/urand_warlock.png","name":"warlock's mirror","id":"UNRAND_WARLOCK_MIRROR","version":"0.27"},
  {"image_url":"https://raw.githubusercontent.com/crawl/crawl/0.27.1/crawl-ref/source/rltiles/item/weapon/artefact/urand_snakebite.png","name":"whip \"Snakebite\"","id":"UNRAND_SNAKEBITE","version":"0.27"},
  {"image_url":"https://raw.githubusercontent.com/crawl/crawl/0.28.0/crawl-ref/source/rltiles/item/weapon/artefact/urand_woodcutters_axe.png","name":"woodcutter's axe","id":"UNRAND_WOODCUTTERS_AXE","version":"0.28"},
  {"image_url":"https://raw.githubusercontent.com/crawl/crawl/0.27.1/crawl-ref/source/rltiles/item/weapon/artefact/spwpn_wrath_of_trog.png","name":"Wrath of Trog","id":"UNRAND_TROG","version":"0.27"},
  {"image_url":"https://raw.githubusercontent.com/crawl/crawl/0.27.1/crawl-ref/source/rltiles/item/weapon/artefact/unrand_zealot_sword.png","name":"zealot's sword","id":"UNRAND_ZEALOT_SWORD","version":"0.27"},
];

export const NameIndex = {};
export const ById = {};

for (let i = 0; i < Metadata.length; i++) {
  const unrand = Metadata[i];
  NameIndex[unrand.name] = i;
  ById[unrand.id] = { ...unrand, i };
}
