const keyMirror = require('src/utils/keyMirror');

const Species = require('src/utils/Species');
const Backgrounds = require('src/utils/Backgrounds');

// prettier-ignore
const Keys = keyMirror({
  v26: true,
  v25: true,
  v24: true,
});

const Versions = {
  [Keys.v26]: '0.26',
  [Keys.v25]: '0.25',
  [Keys.v24]: '0.24',
};

const VersionSpecies = {
  [Versions.v26]: [
    Species.Ba,
    Species.DD,
    Species.DE,
    Species.Dg,
    Species.Ds,
    Species.Dr,
    Species.Fe,
    Species.Fo,
    Species.Gr,
    Species.Gh,
    Species.Gn,
    Species.Ha,
    Species.HO,
    Species.Hu,
    Species.Ko,
    Species.Mf,
    Species.Mi,
    Species.Mu,
    Species.Na,
    Species.Op,
    Species.Og,
    Species.Pa,
    Species.Sp,
    Species.Te,
    Species.Tr,
    Species.Vp,
    Species.VS,
  ],
  [Versions.v25]: [
    Species.Ba,
    Species.Ce,
    Species.DD,
    Species.DE,
    Species.Dg,
    Species.Ds,
    Species.Dr,
    Species.Fe,
    Species.Fo,
    Species.Gr,
    Species.Gh,
    Species.Gn,
    Species.Ha,
    Species.HO,
    Species.Hu,
    Species.Ko,
    Species.Mf,
    Species.Mi,
    Species.Mu,
    Species.Na,
    Species.Op,
    Species.Og,
    Species.Sp,
    Species.Te,
    Species.Tr,
    Species.Vp,
    Species.VS,
  ],
  [Versions.v24]: [
    Species.Ba,
    Species.Ce,
    Species.DD,
    Species.DE,
    Species.Dg,
    Species.Ds,
    Species.Dr,
    Species.Fe,
    Species.Fo,
    Species.Gr,
    Species.Gh,
    Species.Gn,
    Species.Ha,
    Species.HO,
    Species.Hu,
    Species.Ko,
    Species.Mf,
    Species.Mi,
    Species.Mu,
    Species.Na,
    Species.Op,
    Species.Og,
    Species.Sp,
    Species.Te,
    Species.Tr,
    Species.Vp,
    Species.VS,
  ],
};

const VersionBackgrounds = {
  [Versions.v26]: [
    Backgrounds.AE,
    Backgrounds.AK,
    Backgrounds.AM,
    Backgrounds.Ar,
    Backgrounds.As,
    Backgrounds.Be,
    Backgrounds.Cj,
    Backgrounds.CK,
    Backgrounds.De,
    Backgrounds.EE,
    Backgrounds.En,
    Backgrounds.FE,
    Backgrounds.Fi,
    Backgrounds.Gl,
    Backgrounds.Hu,
    Backgrounds.IE,
    Backgrounds.Mo,
    Backgrounds.Ne,
    Backgrounds.Sk,
    Backgrounds.Su,
    Backgrounds.Tm,
    Backgrounds.VM,
    Backgrounds.Wn,
    Backgrounds.Wr,
    Backgrounds.Wz,
  ],
  [Versions.v25]: [
    Backgrounds.AE,
    Backgrounds.AK,
    Backgrounds.AM,
    Backgrounds.Ar,
    Backgrounds.As,
    Backgrounds.Be,
    Backgrounds.Cj,
    Backgrounds.CK,
    Backgrounds.EE,
    Backgrounds.En,
    Backgrounds.FE,
    Backgrounds.Fi,
    Backgrounds.Gl,
    Backgrounds.Hu,
    Backgrounds.IE,
    Backgrounds.Mo,
    Backgrounds.Ne,
    Backgrounds.Sk,
    Backgrounds.Su,
    Backgrounds.Tm,
    Backgrounds.VM,
    Backgrounds.Wn,
    Backgrounds.Wr,
    Backgrounds.Wz,
  ],
  [Versions.v24]: [
    Backgrounds.AE,
    Backgrounds.AK,
    Backgrounds.AM,
    Backgrounds.Ar,
    Backgrounds.As,
    Backgrounds.Be,
    Backgrounds.Cj,
    Backgrounds.CK,
    Backgrounds.EE,
    Backgrounds.En,
    Backgrounds.FE,
    Backgrounds.Fi,
    Backgrounds.Gl,
    Backgrounds.Hu,
    Backgrounds.IE,
    Backgrounds.Mo,
    Backgrounds.Ne,
    Backgrounds.Sk,
    Backgrounds.Su,
    Backgrounds.Tm,
    Backgrounds.VM,
    Backgrounds.Wn,
    Backgrounds.Wr,
    Backgrounds.Wz,
  ],
};

module.exports = {
  ...Versions,
  Species: VersionSpecies,
  Backgrounds: VersionBackgrounds,
};
